spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        filters:
        - StripPrefix=2
        - name: SampleCookie
          args:
            message: hola mi mensaje personalizado para pporoductos
            name: user
            value: adnres
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, abbsbgsds
        - AddResponseHeader=token-response, 2324242
        - AddRequestParameter=name, Andres
        - SetResponseHeader=Content-Type, text/plain